// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://neubbocdgcklzvyjbmvj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ldWJib2NkZ2NrbHp2eWpibXZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA1MzAyNDIsImV4cCI6MjA3NjEwNjI0Mn0.NsQspdbv0ywnKtKYp7Utokq2I9ah2ESkeKG8Cz4Eglo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});